# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & pkg

on:
  workflow_dispatch: ~
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-running:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install pnpm
    - run: npm i pnpm
    - name: install this
    - run: pnpm install
    - name: build this
    - run: pnpm build
    - name: pkg pack
    - run: pnpm install pkg
    - run: pkg package.json -t node18-linux-x64
    - run: pkg package.json -t node18-windows-x64
    - name: Upload a Build uptime-kuma Artifact windows
      uses: actions/upload-artifact@v3.1.2
      with:
        path: uptime-kuma.exe
        name: uptime-kuma-windows
    - name: Upload a Build uptime-kuma Artifact linux
      uses: actions/upload-artifact@v3.1.2
      with:
        path: uptime-kuma
        name: uptime-kuma-linux
        path: uptime-kuma.exe
